# User
security_user_list:
    pattern:  /user/list
    defaults: { _controller: AuthenticationBundle:User:list }

security_user_save:
    pattern:  /user/save
    defaults: { _controller: AuthenticationBundle:User:save }

# Role

security_role_list:
    pattern:  /role/list
    defaults: { _controller: AuthenticationBundle:Role:list }

security_role_save:
    pattern:  /role/save
    defaults: { _controller: AuthenticationBundle:Role:save }
    
# Login

_security_login:
    pattern: /login
    defaults: { _controller: AuthenticationBundle:Security:login }

_security_check:
    pattern: /login_check
