# User
security_user_list:
    pattern:  /user/list.{_format}
    defaults: { _controller: AuthenticationBundle:User:list, _format: json }
    requirements: { _format: (xml|json) }

security_user_save:
    pattern:  /user/save.{_format}
    defaults: { _controller: AuthenticationBundle:User:save, _format: json }
    requirements: { _format: (xml|json) }

# Role

security_role_list:
    pattern:  /role/list.{_format}
    defaults: { _controller: AuthenticationBundle:Role:list, _format: json }
    requirements: { _format: (xml|json) }

security_role_save:
    pattern:  /role/save.{_format}
    defaults: { _controller: AuthenticationBundle:Role:save, _format: json }
    requirements: { _format: (xml|json) }

security_role_delete:
    pattern:  /role/delete.{_format}
    defaults: { _controller: AuthenticationBundle:Role:delete, _format: json }
    requirements: { _format: (xml|json) }
    
# Login

_security_login:
    pattern: /login
    defaults: { _controller: AuthenticationBundle:Security:login }

_security_check:
    pattern: /login_check
