<?php

namespace Equinoxe\AuthenticationBundle\Entity;

/**
 * Test class for Role.
 * Generated by PHPUnit on 2011-02-01 at 08:54:42.
 */
class RoleTest extends \Equinoxe\TestBundle\Test\WebTestCase
{

    /**
     * @var Role
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Role('TEST_ROLE');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @todo Implement testGetRole().
     */
    public function testGetRole()
    {
        $this->assertEquals('TEST_ROLE', $this->object->getRole());
    }

    /**
     * @todo Implement testGetRole().
     */
    public function testToString()
    {
        $this->assertEquals('TEST_ROLE', (string)$this->object);
    }

    public function testUid()
    {
        $this->object->setUid(3);
        $this->assertEquals(3, $this->object->getUid());
    }

    public function testSetRole()
    {
        $this->object->setRole('NEW_ROLE');
        $this->assertEquals('NEW_ROLE', $this->object->getRole());
    }
}
