<?php

namespace Equinoxe\AuthenticationBundle\Entity;

/**
 * Test class for Role.
 * Generated by PHPUnit on 2011-02-01 at 08:54:42.
 */
class RoleTest extends \Equinoxe\TestBundle\Test\WebTestCase
{

    /**
     * @var Role
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Role;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @todo Implement testGetRole().
     */
    public function testGetRole()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
